# Based on
# https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
stages:
  - test

image: python:3.10

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"

cache:
  key:
    files:
      - poetry.lock
    prefix: python-3.10-
  paths:
    - .cache

before_script:
  - python -V
  - pip install poetry
  - poetry config repositories.git-lewisjarednz-domestic_pathways https://gitlab.com/lewisjarednz/domestic_pathways.git
  - poetry config http-basic.git-lewisjarednz-domestic_pathways gitlab-ci-token $CI_JOB_TOKEN
  - poetry config installer.max-workers 5
  - poetry config virtualenvs.create true
  - poetry config virtualenvs.in-project true

test:linting:
  stage: test
  script:
    - poetry install --no-interaction --all-extras
    - poetry run pre-commit run --all-files
    - MYPYPATH=stubs poetry run mypy src notebooks

test:commit-messages:
  stage: test
  except:
    variables:
      - $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^Draft/
  script:
    - pip install commitizen
    - cz check --rev-range dfbc95a1..HEAD
