name: ssp119-low
ssp_scenario: ssp119
output_notebook_dir: dev-output/notebooks

emissions:
  cleaning_operations:
    - input_file: ../../data/raw/input_emissions/SSP_IAM_V2_201811.csv
      filters:
        scenario: SSP1-19
        model: IMAGE
    - input_file: ../../data/raw/input_emissions/SSP_CMIP6_201811.csv
      filters:
        scenario: SSP1-19
        variable: CMIP6 Emissions|*
        region:
          - World
          - R5.2*
      renames:
        - target: CMIP6 Emissions
          to: Baseline Emissions
          dimension: variable
  metadata:
    assumptions: low

  input_scenario: dev-output/ssp119-low/emissions_input.csv
  magicc_scenario: dev-output/ssp119-low/emissions_CR-ssp119-low_magicc.csv
  complete_scenario: dev-output/ssp119-low/emissions_CR-ssp119-low_complete.csv
  complete_scenario_countries: dev-output/ssp119-low/emissions_CR-ssp119-low_countries.csv
  figure_by_sector: dev-output/ssp119-low/plots/emissions_by-sector.pdf
  figure_by_sector_only_modified: dev-output/ssp119-low/plots/emissions_by-sector-modified.pdf
  figure_vs_rcmip: dev-output/ssp119-low/plots/emissions_vs-rcmip.pdf

historical_h2_emissions:
  scenario: ssp245
  baseline_source: ../../data/raw/baseline_h2_sources/petterson_2020.csv
  anthropogenic_proxy:
    "Emissions|H2|Fossil Fuel": Emissions|CO
    "Emissions|H2|Biomass burning": Emissions|BC
    "Emissions|H2|Photochemical production|CH4": Emissions|CH4
    "Emissions|H2|Photochemical production|VOC": Emissions|VOC
  baseline_h2_emissions_regions: dev-output/historical/baseline_h2_emissions_regions.csv
  baseline_h2_emissions_countries: dev-output/historical/baseline_h2_emissions_country.csv
  figure_baseline_by_sector: dev-output/historical/plots/baseline_by-sector.pdf
  figure_baseline_by_source: dev-output/historical/plots/baseline_by-source.pdf
  figure_baseline_by_source_and_sector: dev-output/historical/plots/baseline_by-source-sector.pdf

historical_h2_gridding:
  proxy_mapping: ../../data/raw/gridding/grid_proxy_mapping.csv
  seasonality_mapping: ../../data/raw/gridding/seasonality_mapping_CEDS9.csv
  sector_type: "CEDS9"
  # TODO: make this non-user specific
  grid_data_directory: /Users/jared/code/cr/aneris/data/processed/gridding
  output_directory: dev-output/historical/gridding
  fast: true

input4mips_archive:
  local_archive: ../../data/raw/input4MIPs
  results_archive: dev-output/results
  version: 20230515

delta_emissions:
  inputs:
    share_by_carrier: ../../data/raw/delta_emissions/share_by_carrier_NZE.csv
    leakage_rates: ../../data/raw/delta_emissions/leakage_rates_low.csv
    emissions_intensities_production: ../../data/raw/delta_emissions/emissions_intensities_production_low.csv
    emissions_intensities_combustion: ../../data/raw/delta_emissions/emissions_intensities_combustion_low.csv
  extensions:
    - filters:
        variable:
          - Emissions Intensity|H2|Energy Sector
          - Emissions Intensity|NH3|Energy Sector
        sector: Energy Sector
        product: NOx
      start_year: 2020
      end_year: 2100
      rate: -0.04
  clean:
    share_by_carrier: dev-output/ssp119-low/delta_emissions/share_by_carrier_clean.csv
    leakage_rates: dev-output/ssp119-low/delta_emissions/leakage_rates_clean.csv
    emissions_intensities_production: dev-output/ssp119-low/delta_emissions/emissions_intensities_production_clean.csv
    emissions_intensities_combustion: dev-output/ssp119-low/delta_emissions/emissions_intensities_combustion_clean.csv

  energy_by_carrier: dev-output/ssp119-low/delta_emissions/energy_by_carrier.csv

  delta_emissions_complete: dev-output/ssp119-low/delta_emissions/delta_emissions_complete.csv
  delta_emissions_totals: dev-output/delta_emissions_totals.csv

projected_h2_emissions:
  scenario: "ssp119"
  baseline_source: ../../data/raw/baseline_h2_sources/petterson_2020.csv
  anthropogenic_proxy:
    "Emissions|H2|Fossil Fuel": Emissions|CO
    "Emissions|H2|Biomass burning": Emissions|BC
    "Emissions|H2|Photochemical production|CH4": Emissions|CH4
    "Emissions|H2|Photochemical production|VOC": Emissions|VOC
  baseline_h2_emissions_regions: dev-output/ssp119-low/baseline_h2_emissions_regions.csv
  baseline_h2_emissions_countries: dev-output/ssp119-low/baseline_h2_emissions_country.csv
  figure_baseline_by_sector: dev-output/ssp119-low/plots/baseline_by-sector.pdf
  figure_baseline_by_source: dev-output/ssp119-low/plots/baseline_by-source.pdf
  figure_baseline_by_source_and_sector: dev-output/ssp119-low/plots/baseline_by-source-sector.pdf

projected_gridding:
  proxy_mapping: ../../data/raw/gridding/grid_proxy_mapping.csv
  seasonality_mapping: ../../data/raw/gridding/seasonality_mapping_CEDS9.csv
  sector_type: "CEDS9"
  # TODO: make this non-user specific
  grid_data_directory: /Users/jared/code/cr/aneris/data/processed/gridding
  output_directory: dev-output/ssp119-low/gridding
  fast: true

magicc_runs:
  n_cfgs_to_run: 5
  output_file: ../dev-output/ssp119-low/magicc-output/magicc-concentration-projections.nc
  ar6_probabilistic_distribution_file: ../../data/raw/magicc-bits-and-pieces/magicc-ar6-0fd0f62-f023edb-drawnset/0fd0f62-derived-metrics-id-f023edb-drawnset.json
  test_scenario: ../../data/raw/test-complete-scenario/emissions_complete_CR-IMAGE_ssp119_low.csv
  # this probably belongs in an environment variable if we're perfectly honest
  # because it's platform dependent, @jared what do you think?
  magicc_executable_path: ../../data/raw/magicc-bits-and-pieces/magicc-v7.5.3/bin/magicc-darwin-arm64
  magicc_worker_root_dir: ~/Desktop
  magicc_worker_number: 4

rcmip:
  # TODO: put this in bookshelf
  concentrations_path: ../../data/raw/rcmip/rcmip-concentrations-annual-means-v5-1-0.csv

cmip6_concentrations:
  root_raw_data_dir: ../../data/raw/cmip6-concentrations
  concentration_scenario_ids:
    - IMAGE-ssp119
    - IMAGE-ssp126
    - MESSAGE-GLOBIOM-ssp245
    - REMIND-MAGPIE-ssp534-over
  concentration_variables:
    - mole-fraction-of-carbon-dioxide-in-air
    - mole-fraction-of-methane-in-air

concentration_gridding:
  cmip6_seasonality_and_latitudinal_gradient_path: ../dev-output/ssp119-low/data/interim/cmip6-concentrations-grids/cmip6-seasonality-and-latitudinal-gradient.nc
  interim_gridded_output_dir: ../dev-output/ssp119-low/data/interim/gridded-concentration-projections
  gridded_output_dir: ../dev-output/ssp119-low/data/processed/input4MIPs-gridded-concentration-projections
