name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump_rule:
        type: choice
        description: How to bump the project's version (see https://python-poetry.org/docs/cli/#version)
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
        required: true

jobs:
  bump_version:
    name: "Bump version and create changelog"
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_EMAIL: "ci@climate-resource.com"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Create bump and changelog

        run: |
          BASE_VERSION=`poetry version -s`
          NEW_VERSION=`poetry version -s $BUMP_RULE`
          towncrier build --yes --version v$NEW_VERSION

          git config --global user.name "${{ env.GITHUB_ACTOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"

          git commit -a -m "bump: version $BASE_VERSION -> $NEW_VERSION"
          git tag v$NEW_VERSION
          git push && git push --tags
          echo "Bumped to version $NEW_VERSION"
