name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  mypy:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: "3.10"
          venv-id: "docs"
          poetry-dependency-install-flags: "--all-extras --only 'main,dev'"
          gitlab-access-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      - name: mypy
        run: |
          MYPYPATH=stubs poetry run mypy --install-types --non-interactive src notebooks

  check-dependency-licences:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: "3.10"
          venv-id: "licence-check"
          poetry-dependency-install-flags: "--all-extras"
          gitlab-access-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      - name: Check licences of dependencies
        shell: bash
        run: |
          TEMP_FILE=$(mktemp)
          poetry export --without=dev > $TEMP_FILE
          poetry run liccheck -r $TEMP_FILE -R licence-check.txt
          cat licence-check.txt
